export enum ErrorCommonStrings {
  INTERNAL_SERVER_ERROR = "Internal server error.",
  BAD_INPUT = "BAD_INPUT",
  BAD_REQUEST = "BAD_REQUEST",
  INVALID_USER = "Invalid User",
  INVALID_PASSWORD = "Invalid Password",
  OLD_PASSWORD = "Old Password Is Wrong",
  TOO_MANY_REQUEST = "Too Many Requests",
  UNAUTHORIZED_REQUEST = "UNAUTHORIZED_REQUEST",
  EMAIL_INVALID = "Email Is Invalid",
  USER_NOT_FOUND = "User Not Found",
  INVALID_REQUEST = "Invalid Request",
  UNVERIFIED = "Unverified Email",
  NOT_FOUND = "Not Found",
  NOT_IMPLEMENTED = "Not Implemented",
  ALREADY_EXIST = "Already Exist",
  PLEASE_PROVIDE_ID = "Please provide Id.",
  NOT_AUTHORIZED = "Not Authorized.",
  MISSING_DEVICE = "Missing deviceId in request.",
  DEVICE_NOT_FOUND = "Device not found.",
  DEVICE_ID_REQUIRED = "Device ID is required.",
  DEVICE_ALREADY_EXIST = "Device already registered.",
  NOT_ALLOWED = "MethodNotAllowedError",
  TRANSACTION_FAILED = "transactionFailed",
}
export const localConstant = {
  ERROR_CREATING_ORGANIZATION: "Error creating organization",
  ERROR_CREATING_LOCATION: "Error creating location",
  ERROR_CREATING_EMPLOYEE: "Error creating employee",
  ERROR_CREATING_DEPARTMENT: "Error creating department",
  ERROR_GETTING_ORGANIZATION: "Error getting organization",
  ERROR_UPDATING_NODE: "Error updating node",
  ERROR_DELETING_NODE: "Error deleting node",
};
